#Makefile编写规则
	[要生成的目标文件名称]:[依赖对象]
	[制表符]如何通过依赖对象生成目标对象的编译命令

makefile当中有几个预定义变量
$@ 代表要生成的目标对象
$^ 所有的依赖对象
$< 代表所有依赖对象中的第一个对象
如果有要生成多个对象，就需要正在前边定义一个对象生成所有对象
.PHONY:[对象] 声明伪对象，每次都要生成 

all:test test1
	
test:test.c tmp.c
	gcc test.c tmp.c -o test
	或者
	gcc $^ -o $@
test1:test.c tmp.c
	gcc @< -o $@
#makefile当中，永远只生成第一个对象，生成后则退出

SRC=$(wildcard ./*.c)
OBJ=$(patsubst %.o, %.c, $(SRC))
BIN=./tmp

.PHONY:$(BIN)
$(BIN):S(OBJ)
	gcc $^ -o $@
%.o:%.c
	gcc -c $< -o $@

clean:
	rm -f $(OBJ) $(bin)